--1) CONSULTE TODOS OS VEÍCULOS EXISTENTES NO BD, EXIBINDO A PLACA, MODELO E FABRICANTE DE CADA UM.

SELECT V.PLACA,
       M.NOME_MODELO,
       F.NOME_DO_FABRICANTE
FROM VEICULO V
INNER JOIN MODELO M ON M.CODIGO_MODELO = V.CODIGO_MODELO
INNER JOIN FABRICANTE F ON F.CODIGO_DO_FABRICANTE = M.CODIGO_FABRICANTE;

--2) CONSULTE A QUANTIDADE DE REGISTROS EXISTENTES NA TABELA VEICULO CUJO ANO DE FABRICAÇÃO É DIFERENTE DO ANO DO MODELO.

SELECT COUNT(*)AS QUANTIDADE_VEICULOS
FROM VEICULO V
WHERE V.ANO_FABRICACAO <> V.ANO_MODELO;

--3) CONSULTE A QUANTIDADE DE VEÍCULOS EXISTENTES POR ANO DE FABRICAÇÃO, CONSIDERANDO APENAS OS ANOS DE FABRICAÇÃO EXISTENTES NA TABELA VEICULO.

SELECT V.ANO_FABRICACAO, COUNT(*)AS QUANTIDADE_VEICULOS
FROM VEICULO V
GROUP BY(V.ANO_FABRICACAO)

--4) CONSULTE TODOS OS NOMES DE MODELO DOS FABRICANTES “FORD”, “FIAT” E “HONDA”.

SELECT M.NOME_MODELO 
FROM MODELO M
INNER JOIN FABRICANTE F ON F.CODIGO_DO_FABRICANTE = M.CODIGO_FABRICANTE
WHERE F.NOME_DO_FABRICANTE IN ('FORD', 'FIAT', 'HONDA');

--5) CONSULTE OS VEÍCULOS QUE TEM A PLACA TERMINANDO EM “123”.

SELECT *
FROM VEICULO V
WHERE V.PLACA LIKE '%123';

--6) CONSULTE OS VEÍCULOS FABRICADOS NOS ANOS DE 2001, 2002, 2003, 2004, 2006, 2007 E 2008.

SELECT *
FROM VEICULO V
WHERE V.ANO_FABRICACAO IN('2001', '2002', '2003', '2004', '2006', '2007' , '2008')
ORDER BY V.ANO_FABRICACAO;

--7) CONSULTE OS VEÍCULOS COM ANO DO MODELO ENTRE 1999 E 2016;

SELECT *
FROM VEICULO V
WHERE V.ANO_MODELO BETWEEN 1996 AND 2016
ORDER BY V.ANO_MODELO;

--8) CONSULTE TODOS OS VEÍCULOS DO MODELO “GOL”, DO FABRICANTE “VOLKSWAGEN”.

SELECT V.*,
       M.NOME_MODELO,
       F.NOME_DO_FABRICANTE
FROM VEICULO V
INNER JOIN MODELO M ON M.CODIGO_MODELO = V.CODIGO_MODELO
INNER JOIN FABRICANTE F ON F.CODIGO_DO_FABRICANTE = M.CODIGO_FABRICANTE
WHERE M.NOME_MODELO = 'GOL' AND F.NOME_DO_FABRICANTE='VOLKSWAGEN';

--9) CONSULTE OS VEÍCULOS DO MODELO “GOL”, DO FABRICANTE “VOLKSWAGEN”, QUE FORAM FABRICADOS EM 2010 OU TÊM PLACA INICIANDO COM “X”.

SELECT V.*, M.NOME_MODELO, F.NOME_DO_FABRICANTE
FROM VEICULO V
INNER JOIN MODELO M ON M.CODIGO_MODELO = V.CODIGO_MODELO
INNER JOIN FABRICANTE F ON F.CODIGO_DO_FABRICANTE = M.CODIGO_FABRICANTE
WHERE M.NOME_MODELO = 'GOL'
  AND F.NOME_DO_FABRICANTE='VOLKSWAGEN'
  AND (V.ANO_FABRICACAO = 2010
       OR V.PLACA LIKE'X%') ;

--10) CONSULTE TODOS OS VEÍCULOS DO FABRICANTE “RENAULT” QUE NÃO SEJAM DOS MODELOS “CLIO” NEM “SANDERO”, E QUE FORAM FABRICADOS ANTES DE 2015.

SELECT V.*, M.NOME_MODELO, F.NOME_DO_FABRICANTE
FROM VEICULO V
INNER JOIN MODELO M ON M.CODIGO_MODELO = V.CODIGO_MODELO
INNER JOIN FABRICANTE F ON F.CODIGO_DO_FABRICANTE = M.CODIGO_FABRICANTE
WHERE F.NOME_DO_FABRICANTE='RENAULT'
  AND M.NOME_MODELO NOT IN('CLIO', 'SANDERO')
  AND V.ANO_FABRICACAO < 2015;

--11) CONSULTE A LISTA DE MODELOS EXISTENTES NA TABELA MODELO QUE NÃO POSSUEM VEÍCULOS ASSOCIADOS NA TABELA VEICULO.'

SELECT  M.*
FROM MODELO M
LEFT JOIN VEICULO V ON M.CODIGO_MODELO = V.CODIGO_MODELO
WHERE V.CODIGO_MODELO IS NULL
ORDER BY M.CODIGO_MODELO;

--12) CRIE UM COMANDO PARA ALTERAR PARA 2016 O ANO DE FABRICAÇÃO DE TODOS OS VEÍCULOS DO MODELO “PALIO”, DO FABRICANTE “FIAT”, QUE ESTÃO REGISTRADOS COM ANO DE FABRICAÇÃO EM 1996.'

UPDATE V
SET V.ANO_FABRICACAO = 2016
FROM VEICULO V
INNER JOIN MODELO M ON M.CODIGO_MODELO = V.CODIGO_MODELO
INNER JOIN FABRICANTE F ON F.CODIGO_DO_FABRICANTE = M.CODIGO_FABRICANTE
WHERE M.NOME_MODELO = 'PALIO' 
  AND F.NOME_DO_FABRICANTE = 'FIAT' 
  AND V.ANO_FABRICACAO = 1996;


